name: Feature Request
description: Suggest a new feature or enhancement.
title: "[FR] Your Title Here"
labels: [ feature request ]

body:
    -   type: markdown
        attributes:
            value: |
                Thanks for suggesting a feature! Please provide as much detail as possible.
                
                Some code of conducts to adhere to when submitting a feature request:
                - Do not merge multiple feature requests into one single issue. Create separate issues for each feature requests you have.
                - Do not offer financial or material compensation in exchange for a feature request. This also includes offering to pay for the license once the feature has been implemented.
                - Do not make a personal request for a feature that is not relevant to the project or to the wide range of users.
                  If your feature request starts with _I want this_ or _I need this_, it is likely a personal request and should not be submitted.

    -   type: checkboxes
        id: confirmation
        attributes:
            label: Confirmation
            description: |
                Please confirm the following:
            options:
                -   label: I have read the [Code of Conduct](https://github.com/Hamza417/Felicity/blob/master/CODE_OF_CONDUCT.md)
                    required: true
                -   label: I have searched the existing issues
                    required: true

    -   type: input
        id: feature_description
        attributes:
            label: Feature Description
            description: A clear and concise description of what the feature is and what problem it solves.
            placeholder: Describe the feature here
        validations:
            required: true

    -   type: textarea
        id: solution
        attributes:
            label: Describe the Solution
            description: A clear and concise description of what you want to happen.
            placeholder: Describe the solution here
        validations:
            required: true

    -   type: textarea
        id: additional_context
        attributes:
            label: Additional Context (if applicable)
            description: Add any other context or screenshots about the feature request here.
            placeholder: Provide additional context here
